/* Generated by re2c 4.6 on Tue Sep 22 08:59:55 2026 */
#line 1 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
#include "Lexer.h"

Lexer::Token Lexer::lex(){
  auto yyskip = [&](){ if(*(++YYCURSOR) == '\n'){ ++y; x = 1; }else{ ++x; } };
  auto yypeek = [&](){ return *YYCURSOR; };
  auto yybackup = [&](){ YYMARKER = YYCURSOR; };
  auto yyrestore = [&](){ YYCURSOR = YYMARKER; };
  auto getPosStr = [&](){ return std::string{" at y = " + std::to_string(y) + ", x = " + std::to_string(x)}; };

start:
  t = YYCURSOR;
  tx = x;
  ty = y;

  
#line 19 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
{
	char yych;
	yych = yypeek();;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		case '"': goto yy6;
		case ';': goto yy7;
		case '=': goto yy9;
		case '[': goto yy10;
		case ']': goto yy11;
		default: goto yy2;
	}
yy1:
	yyskip();
#line 65 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ return Token{Token::Type::Finished, "", tx, ty}; }
#line 42 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy2:
	yyskip();
	yych = yypeek();;
	switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ':
		case '"':
		case ';':
		case '=':
		case '[':
		case ']': goto yy3;
		default: goto yy2;
	}
yy3:
#line 32 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ return Token{Token::Type::Identifier, std::string{t, (size_t)(YYCURSOR - t)}, tx, ty};}
#line 64 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy4:
	yyskip();
	yych = yypeek();;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 57 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ goto start; }
#line 80 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy6:
	yyskip();
#line 34 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ Token token{Token::Type::String, "", tx, ty};
            while(YYCURSOR < YYLIMIT){
              if(*YYCURSOR == '"'){
                ++YYCURSOR;
                return token;
              }else if(*YYCURSOR == '\\'){
                if(YYCURSOR + 1 < YYLIMIT){
                  token.text.push_back(*(YYCURSOR + 1));
                  YYCURSOR += 2;
                };
              } if(*YYCURSOR == '\n' || *YYCURSOR == '\r' || *YYCURSOR == 0){
                break;
              }else{
                token.text.push_back(*YYCURSOR);
                ++YYCURSOR;
              }
            }
            lastError = "string is not closed" + getPosStr();
            return Token{Token::Type::Finished, "", tx, ty};
            YYCURSOR = YYLIMIT;
          }
#line 105 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy7:
	yyskip();
	yybackup();
	yych = yypeek();;
	if (yych >= 0x01) goto yy13;
yy8:
#line 60 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ lastError = "unknown char " + std::to_string(yych) + getPosStr(); 
            return Token{Token::Type::Finished, "", tx, ty}; 
            YYCURSOR = YYLIMIT;
          }
#line 117 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy9:
	yyskip();
#line 56 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ goto start; }
#line 122 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy10:
	yyskip();
#line 30 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ return Token{Token::Type::BraceLeft, std::string{t, (size_t)(YYCURSOR - t)}, tx, ty};}
#line 127 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy11:
	yyskip();
#line 31 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ return Token{Token::Type::BraceRight, std::string{t, (size_t)(YYCURSOR - t)}, tx, ty};}
#line 132 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
yy12:
	yyskip();
	yych = yypeek();;
yy13:
	switch (yych) {
		case 0x00: goto yy14;
		case '\n': goto yy15;
		default: goto yy12;
	}
yy14:
	yyrestore();
	goto yy8;
yy15:
	yyskip();
#line 58 "E:/test/test_re2c_template/test05/cmake/Lexer.l"
	{ goto start; }
#line 149 "E:/test/test_re2c_template/test05/src/Lexer.cpp"
}
#line 66 "E:/test/test_re2c_template/test05/cmake/Lexer.l"

}